### ISSUE TITLE
brew install fail

### ISSUE THREAD

**Issue by pyth0n3r** [saltbo/rslocal#1]
Error: Invalid formula: /Users/xer/homebrew/Library/Taps/saltbo/homebrew-bin/Formula/uptoc.rb
uptoc: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the saltbo/bin tap (not Homebrew/brew or Homebrew/core):
  /Users/xer/homebrew/Library/Taps/saltbo/homebrew-bin/Formula/uptoc.rb:6

Error: Cannot tap saltbo/bin: invalid syntax in tap!

**Comment by saltbo** [comment]
fixed, retry again
